name: Find Masked Variable
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      myservice:
        image: alpine:latest
        options: --entrypoint sh
    steps:
      - name: Print Variable Names
        run: |
          echo "=== CHECKING SENSITIVE VARS ==="
          printenv | cut -d= -f1 | sort
